site_name: MLOps Study Docs
site_url: https://clabi-eunsil.github.io/study-docs/
repo_url: https://github.com/clabi-eunsil/study-docs
docs_dir: docs

theme:
  name: material
  language: ko
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: 다크 모드로 전환
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: 라이트 모드로 전환
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - content.code.copy
    - search.suggest

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite

plugins:
  - search
